### ISSUE TITLE
New commits from sourceforge SVN repo are missing

### ISSUE THREAD

**Issue by da-phil** [ptpd/ptpd#1]
It would be good to also have the recent SVN commits here at github.

**Comment by skreuzer** [comment]
A while back I attempted to move the repo from sourceforge to github but due to a series of unfortunate circumstances we had to abort that mission after the repo was converted and moved to github but before other people started using it.

However, I finally got the go ahead to do the conversion again so I just redid everything and pushed it here. At this point development of ptpd will happen here and we are going to stop using SF

**Comment by da-phil** [comment]
That sounds great @skreuzer, thank you.
It is so much better to collaborate here at github.
